# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        # I like to configure my services, so I disabled the autoconfigure
        autoconfigure: false
        # Since I'm manually configuring my services, I want them public
        public: true



    ##### Repositories

    app.repository.url:
        class: AppBundle\Entity\Repository\UrlRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: [ AppBundle\Entity\Url ]
        tags:
            - { name: 'doctrine.repository_service' }

    ##### Controllers

    app.controller.url:
        class: AppBundle\Controller\UrlController
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ['@service_container']]
            - [setUrlHelper, ['@app.helper.url']]


    ##### Helpers

    app.helper.url:
        class: AppBundle\Helper\UrlHelper
        calls:
            - [setUrlRepository, ['@app.repository.url']]
