# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        # I like to configure my services, so I disabled the autoconfigure
        autoconfigure: false
        # Since I'm manually configuring my services, I want them public
        public: true

    # This is not in use
    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # This is not in use
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    ##### Repositories

    app.repository.url:
        class: AppBundle\Entity\Repository\UrlRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: [ AppBundle\Entity\Url ]
        tags:
            - { name: 'doctrine.repository_service' }

    ##### Controllers

    app.controller.url:
        class: AppBundle\Controller\UrlController
        calls:
            - [setUrlRepository, ['@app.repository.url']]

    ##### Helpers

    app.helper.url:
        class: AppBundle\Helper\UrlHelper
        calls:
            - [setUrlRepository, ['@app.repository.url']]
            - [setEntityManager, ['@doctrine.orm.entity_manager']]

